### ISSUE TITLE
Multiple issues trying to install via the "full installation" switch

### ISSUE THREAD

**Issue by davidworkman9** [xtuple/xtuple-admin-utility#128]
I run into the following when running the `xtuple-utility.sh` script:

```
22:28:27 xtuple >> Creating upstart script using filename /etc/init/xtuple-xtuple-web.conf

/etc/xtuple/4.11.1/xtuple-web/config.js:30
      port: ,
            ^
<<ERROR 2018-01-02T22:28:27.554Z>> Unrecoverable exception. Unexpected token ,SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.build (/opt/xtuple/4.11.1/xtuple-web/xtuple/scripts/lib/build_all.js:123:16)
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/scripts/build_app.js:35:3
    at Object.<anonymous> (/opt/xtuple/4.11.1/xtuple-web/xtuple/scripts/build_app.js:55:2)
    at Module._compile (module.js:456:26)
xtuple-xtuple-web: unrecognized service
```

If I fix the config file, by filling out the empty port locations my own ports I then run into an issue running it:

```
<<ERROR 2018-01-02T22:37:05.821Z>> Database Error! function xt.refresh_share_user_cache() does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.823Z>> Database Error! Last query was: select xt.refresh_share_user_cache()
<<ERROR 2018-01-02T22:37:05.824Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.827Z>> Database Error! function xt.post(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.828Z>> Database Error! Last query was: select xt.post($${"nameSpace":"XT","type":"Session","dispatch":{"functionName":"schema","parameters":"xm"},"username":"admin"}$$) as request
<<ERROR 2018-01-02T22:37:05.828Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.836Z>> Database Error! function xt.post(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.837Z>> Database Error! Last query was: select xt.post($${"nameSpace":"XT","type":"Session","dispatch":{"functionName":"schema","parameters":"sys"},"username":"admin"}$$) as request
<<ERROR 2018-01-02T22:37:05.838Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.841Z>> Database Error! function xt.get(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.842Z>> Database Error! Last query was: select xt.get($${"nameSpace":"SYS","type":"SessionStore","username":"node"}$$) as request
<<ERROR 2018-01-02T22:37:05.843Z>> Database Error! DB name = 4111
<<ERROR 2018-01-02T22:37:05.847Z>> Database Error! function xt.post(unknown) does not exist Please fix this!!!
<<ERROR 2018-01-02T22:37:05.848Z>> Database Error! Last query was: select xt.post($${"nameSpace":"XT","type":"Session","dispatch":{"functionName":"privileges","parameters":null},"username":"admin"}$$) as request
<<ERROR 2018-01-02T22:37:05.848Z>> Database Error! DB name = 4111
schema error { '0':
   { code: 'xt1001',
     params: { error: [Object] },
     messageKey: '_datasourceError',
     message: [Function] } }
schema error { '0':
   { code: 'xt1001',
     params: { error: [Object] },
     messageKey: '_datasourceError',
     message: [Function] } }
<<LOG 2018-01-02T22:37:05.856Z>> Share Users Cache warming errors:{ [error: function xt.refresh_share_user_cache() does not exist]
  length: 221,
  name: 'error',
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'parse_func.c',
  line: '523',
  routine: 'ParseFuncOrColumn' }
Trace: Share Users Cache warming errors:
    at cacheShareUsersWarmed (/opt/xtuple/4.11.1/xtuple-web/xtuple/node-datasource/main.js:194:15)
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/node-datasource/lib/ext/datasource.js:282:15
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:278:11
    at /opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/lib/pool.js:38:18
    at null.<anonymous> (/opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/lib/client.js:137:7)
    at g (events.js:180:16)
    at emit (events.js:117:20)
    at Socket.<anonymous> (/opt/xtuple/4.11.1/xtuple-web/xtuple/node_modules/pg/lib/connection.js:87:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
```

**Comment by gilmoskowitz** [comment]
Fixed by #129
