### ISSUE TITLE
Web Client Stops Working

### ISSUE THREAD

**Issue by zrichmond** [xtuple/xtuple-admin-utility#61]
For some reason, that I have not yet discovered, even after may tries,  the web client stops working after a reboot.  I have successfully installed and logged in via the web client even sporting a copy of my own database.  I have even cloned a working instance of the VirtualBox VM, created it's own host-only network and connect to the clone's web client successfully navigating the xtuple web application.  However, as soon as I reboot the instance, I only get as far as the login page, which oddly enough is being served.  Checking the nginx access and error logs (including the xtuple instance ones) yields nothing.

Maybe the problem is that the config.js defaults to

```
databaseServer: {
        hostname: "localhost",
        port: "5432",
        user: "admin",
        password: "admin"

```

and I haven't had a good automatic install?

**Comment by zrichmond** [comment]
Okay this is as far as I can get for the day:


```
tail -vf /var/log/node-datasource-4.8.1-ihsco_webdev.log

...snip...
<<ERROR 2015-09-20T00:34:13.066Z>> Unrecoverable exception. Object false has no method 'get'TypeError: Object false has no method 'get'
    at parse (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/lib/backbone-x/source/model_mixin.js:890:39)
    at XM.ModelMixin.parse (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/lib/backbone-x/source/model_mixin.js:903:14)
    at options.success (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/node_modules/backbone/backbone.js:419:30)
    at options.success (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/lib/backbone-x/source/model_mixin.js:1238:11)
    at complete (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/node-datasource/lib/ext/datasource.js:317:31)
    at queryCallback [as callback] (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/node-datasource/lib/ext/datasource.js:247:13)
    at Query.handleReadyForQuery (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/node_modules/pg/lib/query.js:99:10)
    at null.<anonymous> (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/node_modules/pg/lib/client.js:150:24)
    at emit (events.js:117:20)
    at Socket.<anonymous> (/opt/xtuple/4.8.1/ihsco_webdev/xtuple/node_modules/pg/lib/connection.js:87:12)
```

**Comment by zrichmond** [comment]
FYI I can login to the same VM with pgadmin and desktop client with the admin user I was able to configure.

**Comment by zrichmond** [comment]
Essentially not having a clean install due to an unidentified network issue, left the state of the server undetermined.  See #60 for details. If I get a chance to get a working solution to the failed install I'll reopen and document here.
